services:

# Front
  red_tetris:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    networks:
      - red_tetris_network
    restart: always
    volumes:
      - ./app/:/usr/app
    ports:
      - "5173:5173"
      - "3000:3000"
    depends_on:
      - red_tetris_db

# Postgres
  red_tetris_db:
    image: postgres
    networks:
      - red_tetris_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

networks:
  red_tetris_network:
    name: red_tetris_network
    driver: bridge