services:

# Front
  # red_tetris:
  #   build:
  #     context: ./front
  #   networks:
  #     - red_tetris_network
  #   restart: always
  #   volumes:
  #     - ./front/:/usr/app/front
  #   ports:
  #     - "5173:5173"

# Postgres
  red_tetris_db:
    image: postgres
    networks:
      - red_tetris_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

networks:
  red_tetris_network:
    name: red_tetris_network
    driver: bridge