services:
  # Front-end
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - red_tetris_network
    volumes:
      - frontend_dist:/usr/src/app/dist

  # Back-end
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    networks:
      - red_tetris_network
    volumes:
      - frontend_dist:/usr/src/app/dist
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: red_tetris_db
      FRONT_DIST_PATH: ${FRONT_DIST_PATH}
    ports:
      - "3000:3000"
    depends_on:
      - frontend
      - red_tetris_db

  # Database
  red_tetris_db:
    image: postgres
    networks:
      - red_tetris_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

networks:
  red_tetris_network:
    name: red_tetris_network
    driver: bridge

volumes:
  frontend_dist: